# Generated by Django 5.0.4 on 2024-07-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicantprofile",
            name="certificates",
            field=models.FileField(
                blank=True, max_length=250, null=True, upload_to="certificates/"
            ),
        ),
        migrations.AddField(
            model_name="applicantprofile",
            name="resume",
            field=models.FileField(
                blank=True, max_length=250, null=True, upload_to="resumes/"
            ),
        ),
    ]
