# Generated by Django 5.0.4 on 2024-07-08 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicants", "0002_applicantprofile_certificates_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Qualification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school", models.CharField(max_length=255)),
                ("qualification", models.CharField(max_length=255)),
                ("cgpa_or_percentage", models.CharField(max_length=10)),
                ("description", models.TextField(blank=True, null=True)),
                ("stream", models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name="applicantprofile",
            name="applicant",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students_qual",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="applicantprofile",
            name="highest_qualification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="applicants.qualification",
            ),
        ),
    ]
