# Generated by Django 5.0.4 on 2024-07-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicants", "0003_qualification_alter_applicantprofile_applicant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicantprofile",
            name="highest_qualification",
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name="Qualification",
        ),
    ]
