# Generated by Django 5.0.4 on 2024-07-09 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicants", "0004_alter_applicantprofile_highest_qualification_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="applicantprofile",
            name="certificates",
        ),
        migrations.RemoveField(
            model_name="applicantprofile",
            name="resume",
        ),
        migrations.AlterField(
            model_name="applicantprofile",
            name="applicant",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
