# Generated by Django 5.0.6 on 2024-06-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='job_attachments/'),
        ),
    ]
