# Generated by Django 5.0.4 on 2024-05-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="custom_ques",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
