# Generated by Django 5.0.6 on 2024-06-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_remove_job_attachment_organisation_annual_revenue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='created_by',
        ),
        migrations.AddField(
            model_name='organisation',
            name='user_email',
            field=models.EmailField(default='admin@example.com', max_length=254, unique=True),
        ),
    ]
