# Generated by Django 5.0.6 on 2024-06-20 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_organisation_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='user_email',
            new_name='email',
        ),
    ]
