# Generated by Django 5.0.6 on 2024-06-20 10:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0006_rename_user_email_organisation_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Organisation',
            new_name='Organization',
        ),
    ]
