# Generated by Django 5.0.6 on 2024-06-20 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0007_rename_organisation_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='otp_created_at',
        ),
    ]
