# Generated by Django 5.0.6 on 2024-06-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0008_remove_organization_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
