# Generated by Django 5.0.6 on 2024-06-21 03:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0010_organization_unique_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Organization',
            new_name='Organisation',
        ),
    ]
