# Generated by Django 5.0.4 on 2024-06-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0011_rename_organization_organisation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
