# Generated by Django 5.0.4 on 2024-06-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0012_alter_organisation_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="email",
            field=models.EmailField(
                default="admin@example.com", max_length=254, unique=True
            ),
        ),
    ]
