# Generated by Django 5.0.4 on 2024-07-02 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0013_alter_organisation_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organisation",
            name="email",
        ),
    ]
