# Generated by Django 5.0.4 on 2024-07-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0014_remove_organisation_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="email",
            field=models.EmailField(
                default="admin@example.com", max_length=254, unique=True
            ),
        ),
    ]
