# Generated by Django 5.0.4 on 2024-07-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0015_organisation_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="location",
            field=models.CharField(default="jaipur", max_length=100),
        ),
    ]
