# Generated by Django 5.0.4 on 2024-05-27 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_customgoogletokencomposite"),
    ]

    operations = [
        migrations.AddField(
            model_name="customgoogletokencomposite",
            name="refresh_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
